# yazi.toml
#-----------
# show hidden
[manager]
show_hidden = true

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]
prepend_fetchers = [
  { id = "git", name = "*", run  = "git" },
  { id = "git", name = "*/", run  = "git" },
]

[preview]
ueberzug_offset = [15, 4, 80, 40]
